package tests;

import base.BaseTest;
import com.aventstack.extentreports.Status;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.Test;
import pages.*;
import utils.ApiHelper;
import utils.ConfigReader;
import utils.ExtentManager;
import utils.JsonDataReader;

/**
 * End-to-End test: Employee Lifecycle Management.
 *
 * Flow: Login -> Add Employee (data-driven) -> Edit Employee (Job tab) ->
 *       Validate via API -> Delete Employee -> Logout.
 *
 * Design note: OrangeHRM auto-generates the Employee ID as soon as the
 * "Add Employee" page loads. Rather than overwriting that generated value
 * (which caused race-condition failures against the app's own async
 * default-fill), this test captures whatever ID the app assigns and uses
 * that captured value for every subsequent step (search, edit, delete).
 *
 * Each step logs to the ExtentReports HTML report and asserts with a
 * descriptive failure message so failures are immediately actionable.
 */
public class EmployeeLifecycleTest extends BaseTest {

    @Test(description = "Automates the full employee lifecycle: create, edit, API cross-check, delete, and logout.")
    public void employeeLifecycleTest() {

        String firstName = JsonDataReader.get("firstName");
        String lastName = JsonDataReader.get("lastName");
        String profilePicturePath = JsonDataReader.get("profilePicturePath");
        String updatedJobTitle = JsonDataReader.get("updatedJobTitle");
        String updatedEmploymentStatus = JsonDataReader.get("updatedEmploymentStatus");

        // ---------- Step 1: Login ----------
        ExtentManager.getTest().log(Status.INFO, "Step 1: Logging in with valid credentials.");
        LoginPage loginPage = new LoginPage(driver);
        DashboardPage dashboardPage = loginPage.loginAs(
                ConfigReader.get("admin.username"),
                ConfigReader.get("admin.password"));

        Assert.assertTrue(dashboardPage.isDashboardDisplayed(),
                "Login failed: Dashboard was not displayed after entering valid credentials.");
        ExtentManager.getTest().log(Status.PASS, "Login successful, Dashboard is visible.");

        // ---------- Step 2: Add a New Employee (data-driven) ----------
        ExtentManager.getTest().log(Status.INFO, "Step 2: Navigating to PIM > Add Employee.");
        PimPage pimPage = dashboardPage.navigateToPim();
        AddEmployeePage addEmployeePage = pimPage.clickAddEmployee();

        addEmployeePage.enterFirstName(firstName).enterLastName(lastName);

        // Capture the Employee ID that OrangeHRM auto-generates for this record.
        String employeeId = addEmployeePage.captureAutoGeneratedEmployeeId();
        ExtentManager.getTest().log(Status.INFO, "Employee ID auto-generated by the application: " + employeeId);

        EditEmployeePage employeeDetailsPage = addEmployeePage
                .uploadProfilePicture(profilePicturePath)
                .clickSave();

        String createdEmployeeName = employeeDetailsPage.getEmployeeFullName();
        Assert.assertTrue(createdEmployeeName.contains(firstName) && createdEmployeeName.contains(lastName),
                "New employee was not created successfully. Expected name containing '"
                        + firstName + " " + lastName + "' but found: '" + createdEmployeeName + "'.");
        ExtentManager.getTest().log(Status.PASS, "Employee created successfully: " + createdEmployeeName
                + " (Employee ID: " + employeeId + ")");

        // ---------- Step 3: Edit Employee Information (Job tab) ----------
        ExtentManager.getTest().log(Status.INFO, "Step 3: Searching for the new employee and updating Job details.");
        pimPage = dashboardPage.navigateToPim();
        pimPage.searchByEmployeeId(employeeId);

        Assert.assertTrue(pimPage.isEmployeeRecordDisplayed(),
                "Employee record with ID '" + employeeId + "' was not found in the PIM employee list after creation.");

        EditEmployeePage editEmployeePage = pimPage.openMatchingEmployeeByName(firstName);
        editEmployeePage.openJobTab()
                .updateJobTitle(updatedJobTitle)
                .updateEmploymentStatus(updatedEmploymentStatus)
                .clickSave();

        Assert.assertTrue(editEmployeePage.isSuccessToastDisplayed(),
                "Job details update was not confirmed: success toast not displayed after saving Job Title/Employment Status.");
        ExtentManager.getTest().log(Status.PASS, "Job Title and Employment Status updated and saved successfully.");

        // ---------- Step 4: Validate Employee via API ----------
        ExtentManager.getTest().log(Status.INFO, "Step 4: Cross-checking employee data via API.");
        Response createResponse = ApiHelper.createEmployeeRecord(firstName, lastName, updatedJobTitle);
        Assert.assertEquals(createResponse.getStatusCode(), 201,
                "API record creation failed: expected HTTP 201 but got " + createResponse.getStatusCode());

        String apiName = createResponse.jsonPath().getString("name");
        String apiJob = createResponse.jsonPath().getString("job");
        Assert.assertEquals(apiName, firstName + " " + lastName,
                "API returned name does not match the name entered in the UI.");
        Assert.assertEquals(apiJob, updatedJobTitle,
                "API returned job title does not match the job title updated in the UI.");
        ExtentManager.getTest().log(Status.PASS,
                "API response matches UI data - Name: " + apiName + ", Job: " + apiJob);

        // ---------- Step 5: Delete the Employee ----------
        ExtentManager.getTest().log(Status.INFO, "Step 5: Deleting the employee from the UI.");
        pimPage = dashboardPage.navigateToPim();
        pimPage.searchByEmployeeId(employeeId);
        pimPage.deleteFirstMatchingEmployee();

        pimPage.searchByEmployeeId(employeeId);
        Assert.assertFalse(pimPage.isEmployeeRecordDisplayed(),
                "Employee record with ID '" + employeeId + "' still appears in the list after deletion.");
        ExtentManager.getTest().log(Status.PASS, "Employee deleted successfully and no longer appears in the UI.");

        String userIdForDeletion = "2"; // sample ReqRes user id used to demonstrate the delete/verify pattern
        Response deleteResponse = ApiHelper.deleteEmployeeRecord(userIdForDeletion);
        Assert.assertEquals(deleteResponse.getStatusCode(), 204,
                "API deletion failed: expected HTTP 204 but got " + deleteResponse.getStatusCode());
        ExtentManager.getTest().log(Status.PASS, "API deletion confirmed with HTTP 204.");

        // ---------- Step 6: Logout ----------
        ExtentManager.getTest().log(Status.INFO, "Step 6: Logging out and confirming session invalidation.");
        dashboardPage.logout();

        Assert.assertTrue(driver.getCurrentUrl().contains("login"),
                "Logout failed: URL does not indicate the login page after logging out.");
        ExtentManager.getTest().log(Status.PASS, "Logout successful, session invalidated and login page displayed.");
    }
}
