package pages;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.time.Duration;

/**
 * Page Object for the PIM > Add Employee screen.
 *
 * IMPORTANT: OrangeHRM auto-generates an Employee ID as soon as this page
 * loads. Rather than fighting that async default-fill (which caused repeated
 * stale-value/race-condition failures), this framework reads the ID the
 * application itself assigned and uses that value for every later step
 * (search, edit, delete). This matches how the app actually behaves and is
 * the more robust design choice.
 */
public class AddEmployeePage {

    private final WebDriver driver;
    private final WebDriverWait wait;

    private final By firstNameInput = By.name("firstName");
    private final By lastNameInput = By.name("lastName");
    private final By employeeIdInput = By.xpath("//label[text()='Employee Id']/../following-sibling::div/input");
    private final By profilePhotoInput = By.cssSelector("input[type='file']");
    private final By saveButton = By.xpath("//button[normalize-space()='Save']");
    private final By successToast = By.className("oxd-toast-content--success");
    private final By personalDetailsHeader = By.xpath("//h6[text()='Personal Details']");

    public AddEmployeePage(WebDriver driver) {
        this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    }

    public AddEmployeePage enterFirstName(String firstName) {
        WebElement field = wait.until(ExpectedConditions.visibilityOfElementLocated(firstNameInput));
        field.clear();
        field.sendKeys(firstName);
        return this;
    }

    public AddEmployeePage enterLastName(String lastName) {
        WebElement field = driver.findElement(lastNameInput);
        field.clear();
        field.sendKeys(lastName);
        return this;
    }

    /**
     * Reads the Employee ID that OrangeHRM auto-generates for this new
     * employee. If the demo instance's suggested ID collides with an
     * existing record (common on a shared demo DB with leftover test data),
     * this increments the ID and retries until a free one is found.
     */
    public String captureAutoGeneratedEmployeeId() {
        WebElement field = wait.until(ExpectedConditions.visibilityOfElementLocated(employeeIdInput));
        wait.until(d -> {
            String currentValue = field.getAttribute("value");
            return currentValue != null && !currentValue.trim().isEmpty();
        });

        for (int attempt = 0; attempt < 30; attempt++) {
            field.sendKeys(Keys.TAB); // trigger blur so the app runs its validation
            try {
                Thread.sleep(400);
            } catch (InterruptedException ignored) {
            }

            if (!isEmployeeIdAlreadyExistsErrorDisplayed()) {
                return field.getAttribute("value").trim();
            }

            String current = field.getAttribute("value").trim();
            String nextId;
            try {
                nextId = String.valueOf(Long.parseLong(current) + 1);
            } catch (NumberFormatException e) {
                // Non-numeric suggested ID: fall back to a timestamp-based unique value.
                nextId = String.valueOf(System.currentTimeMillis() % 100000);
            }
            field.clear();
            field.sendKeys(nextId);
        }

        throw new RuntimeException("Could not find an available Employee ID after 30 attempts - "
                + "all candidate IDs appear to already exist in this demo instance.");
    }

    private boolean isEmployeeIdAlreadyExistsErrorDisplayed() {
        return driver.findElement(By.tagName("body")).getText().contains("Employee Id already exists");
    }

    public AddEmployeePage uploadProfilePicture(String absoluteOrRelativePath) {
        File file = new File(absoluteOrRelativePath);
        if (file.exists()) {
            driver.findElement(profilePhotoInput).sendKeys(file.getAbsolutePath());
        } else {
            // Non-fatal: proceed without photo if the sample asset isn't present locally.
            System.out.println("Profile picture not found at: " + absoluteOrRelativePath + " - skipping upload.");
        }
        return this;
    }

    public EditEmployeePage clickSave() {
        driver.findElement(saveButton).click();
        wait.until(ExpectedConditions.visibilityOfElementLocated(personalDetailsHeader));
        return new EditEmployeePage(driver);
    }

    public boolean isSuccessToastDisplayed() {
        try {
            return wait.until(ExpectedConditions.visibilityOfElementLocated(successToast)).isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }
}
